# Generated by Django 5.2.8 on 2025-12-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('empresa', 'sigla')},
        ),
    ]
